### ISSUE TITLE
repo deletion

### ISSUE THREAD

**Issue by alicetragedy** [alicetragedy/wpaustria#5]
I'd like to delete this repo, as it's not of much relevance anymore for me. 
Is it a repo I could transfer to either one of you @franz-josef-kaiser @kraftner or am I free to delete?
Please let me know by Wednesday, December 16th (19:00 CET). Thanks.

**Comment by franz-josef-kaiser** [comment]
@alicetragedy Move to trash :)

**Comment by kraftner** [comment]
Shift+Del Enter

**Comment by alicetragedy** [comment]
:skull:
